# Inverse Kinematics Optimization Parameters

# Base values for penalties (will be divided by N in the script)
epsilon_base: 8e-1  # Binary Regularization
eta_base: 3e0      # Bend Penalty  
kappa_base: 1e-2    # Smoothness Penalty 

# Optimizer settings
max_iter: 300
num_starts: 50

# Binary search refinement
num_critical_joints: 5
